# DigitalOcean App Platform Configuration
name: bidscents-marketplace
region: sgp1

services:
- name: bidscents-app
  source_dir: /
  github:
    repo: your-username/bidscents-marketplace  # Update with your GitHub repo
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: SUPABASE_URL
    value: https://rjazuitnzsximznfcbfw.supabase.co/
  - key: SUPABASE_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYXp1aXRuenN4aW16bmZjYmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzc2NDQsImV4cCI6MjA2MDIxMzY0NH0.Nxz6r39jRmCD1lEEglpYaWnSD2nKbLeGnBq2jtnrdqw
  - key: SUPABASE_SERVICE_ROLE_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYXp1aXRuenN4aW16bmZjYmZ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDYzNzY0NCwiZXhwIjoyMDYwMjEzNjQ0fQ.mI8o9usf8pmYUBIUzXZK0_GD1jIhDgOwSMNNDNO6Kco
  - key: VITE_SUPABASE_URL
    value: https://rjazuitnzsximznfcbfw.supabase.co/
  - key: VITE_SUPABASE_ANON_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYXp1aXRuenN4aW16bmZjYmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzc2NDQsImV4cCI6MjA2MDIxMzY0NH0.Nxz6r39jRmCD1lEEglpYaWnSD2nKbLeGnBq2jtnrdqw
  - key: JWT_SECRET
    type: SECRET
    value: YOUR_STRONG_JWT_SECRET_KEY
  - key: JWT_EXPIRES_IN
    value: "24h"
  - key: MESSAGE_ENCRYPTION_KEY
    type: SECRET
    value: YOUR_STRONG_ENCRYPTION_KEY
  - key: BILLPLZ_BASE_URL
    value: https://www.billplz.com/api
  - key: BILLPLZ_SECRET_KEY
    type: SECRET
    value: YOUR_PRODUCTION_BILLPLZ_SECRET_KEY
  - key: BILLPLZ_XSIGN_KEY
    type: SECRET
    value: YOUR_PRODUCTION_BILLPLZ_XSIGN_KEY
  - key: BILLPLZ_COLLECTION_ID
    value: YOUR_PRODUCTION_COLLECTION_ID
  - key: DEMO_MODE
    value: "false"
  - key: APP_URL
    value: https://bidscents-2025-scsjl.ondigitalocean.app
  - key: CLIENT_URL
    value: https://bidscents-2025-scsjl.ondigitalocean.app

domains:
- domain: your-domain.com  # Update with your domain
  type: PRIMARY
- domain: www.your-domain.com  # Update with your domain
  type: ALIAS

alerts:
- rule: CPU_UTILIZATION
  disabled: false
- rule: MEM_UTILIZATION
  disabled: false